=== stormworm29/Programming-Snippets/Java/Complete-Java-Exercies/Exercises/books.dtd
<!ELEMENT books (book)+ >
<!ELEMENT book (name, author+, prize?)>
<!ATTLIST book id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT prize (#PCDATA)>

=== stormworm29/Programming-Snippets/Java/Complete-Java-Exercies/Exercises/books.xml
<!DOCTYPE books SYSTEM "books.dtd">
<books>
	<book id="a1">
		<name>java</name>
		<author>james</author>
		<prize>200</prize>
	</book>	
	<book id="a2">
		<name>xml</name>
		<author>jack</author>
		<prize>200</prize>
	</book>	
	<book id="a3">
		<name>hibernate</name>
		<author>king</author>
		<prize>300</prize>
	</book>	
</books>
